This project is aimed at introducing concepts of Classification, Algorithms and Feature Selection 

UCI Mushroom Data Set available in http://archive.ics.uci.edu/ml/datasets/Mushroom?ref=datanews.io and is used for classifying mushrooms as poisonous or edible.


In [15]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

mush_df = pd.read_csv('https://raw.githubusercontent.com/rajeshunnikrishnan/Applied-Machine-Learning-in-Python/master/mushrooms.csv')

#Convert categorical variable in to dummy/indicator variable. mush_df has 23 columns and get_dummies create a dataframw with 119 columns. 
#For every column in the original dataframe, get_dummies create  columns for every unique value for that column. Each value is 
#then quanitifed using 1 or 0
mush_df2 = pd.get_dummies(mush_df)

X_mush = mush_df2.iloc[:,2:]
y_mush = mush_df2.iloc[:,1]

X_train2, X_test2, y_train2, y_test2 = train_test_split(X_mush, y_mush, random_state=0)
# For performance reasons in Questions 6 and 7, we will create a smaller version of the
# entire mushroom dataset for use in those questions.  For simplicity we'll just re-use
# the 25% test split created above as the representative subset.
# Use the variables X_subset, y_subset for Questions 6 and 7.
X_subset = X_test2
y_subset = y_test2

Identify top 5 features in the dataset using Decision Tree Classifier.DecisionTreeClassifier is a class capable of doing multiclass classification 

In [17]:
def feature_importance():
    from sklearn.tree import DecisionTreeClassifier
    lst=[]
       
    clf = DecisionTreeClassifier().fit(X_train2, y_train2)
    for i in (clf.feature_importances_.argsort()[::-1][:5]):
        lst.append(X_train2.columns[i])
    return (lst)

feature_importance()

['odor_n',
 'stalk_root_c',
 'stalk_root_r',
 'spore_print_color_r',
 'spore_print_color_u']

Determine training and test scores for a Support Vector Classifier (SVC) with radial basis kernel. validation_curve class uses multipel combination of train and test data splits and computes the scores. In this example, 6 values of gamma from 0.0001 to 10 (i.e. np.logspace(-4,1,6)) is used to explore the impact. 

For each level of gamma, validation_curve will fit 3 models on different subsets of the data, returning two 6x3 (6 levels of gamma x 3 fits per level) arrays of the scores for the training and test sets.

Return mean score across the three models for each level of gamma for both arrays, creating two arrays of length 6

In [22]:
def answer_six():
    from sklearn.svm import SVC
    from sklearn.model_selection import validation_curve
    
    clf=SVC(C=1,kernel='rbf',random_state=None)
    param_range=np.logspace(-4,1,6)
    
    train_scores, test_scores=validation_curve(clf, X_subset, y_subset,
                                            param_name='gamma',
                                            param_range=param_range, cv=3, scoring='accuracy')
    print('Train Scores:','\n', train_scores,'\n')
    print('Test Scores:', '\n',test_scores,'\n')
    print ('Average Train score for each gamma:','\n',np.mean(train_scores,axis=1),'\n')
    print ('Average Test score for each gamma:','\n',np.mean(test_scores,axis=1))
answer_six()

Train Scores: 
 [[ 0.58906135  0.55686854  0.55350554]
 [ 0.93200296  0.9254062   0.93726937]
 [ 0.99039172  0.99039882  0.9904059 ]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]
 [ 1.          1.          1.        ]] 

Test Scores: 
 [[ 0.58554572  0.56277696  0.55473373]
 [ 0.91445428  0.95125554  0.92307692]
 [ 0.98967552  0.99113737  0.98816568]
 [ 1.          1.          1.        ]
 [ 0.98967552  0.9985229   0.99704142]
 [ 0.52212389  0.52289513  0.52218935]] 

Average Train score for each gamma: 
 [ 0.56647847  0.93155951  0.99039881  1.          1.          1.        ] 

Average Test score for each gamma: 
 [ 0.56768547  0.92959558  0.98965952  1.          0.99507994  0.52240279]
